# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d90fb38679ae6fdb3f6222cf3b898446876711c1e66a77b19bb99f7fdfea2a3c05f49e33def55732cab75df78b700b95ba10e11239e8b7f94f68a70a015ad57f

test:
  secret_key_base: 8c108b1591c6cf3f76eec3050a3e151edd58d6c6b80896c41f9d98e5f15e695f284d59497513a5d99d6df8ada35dc06be9267a476045d83556930db0db743d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
